CREATE TABLE `TB_USUARIO` (
	`ID_USUARIO` bigint NOT NULL AUTO_INCREMENT,
	`NOME` varchar(50) NOT NULL,
	`CPF` int(11) NOT NULL UNIQUE,
	`DATA_NASCIMENTO` DATE NOT NULL,
	`SENHA` varchar(10) NOT NULL,
	`TIPO_USUARIO` varchar(30) NOT NULL,
	`CRM` varchar(10),
	`ID_ENDERECO` bigint NOT NULL,
	`ID_POSTAGEM` bigint NOT NULL,
	`ID_CONSULTA` int NOT NULL,
	PRIMARY KEY (`ID_USUARIO`)
);

CREATE TABLE `TB_ENDERECO` (
	`ID_ENDERECO` bigint NOT NULL AUTO_INCREMENT,
	`CEP` int(8) NOT NULL,
	`BAIRRO` varchar(20) NOT NULL,
	`RUA` varchar(30) NOT NULL,
	`NUMERO` int(10) NOT NULL,
	`COMPLEMENTO` varchar(20) NOT NULL,
	PRIMARY KEY (`ID_ENDERECO`)
);

CREATE TABLE `TB_POSTAGEM` (
	`ID_POSTAGEM` bigint NOT NULL AUTO_INCREMENT,
	`DESCRICAO` varchar(1000) NOT NULL,
	`DATA_POSTAGEM` DATE NOT NULL,
	`CURTIDA` bigint NOT NULL,
	`ID_TEMA` bigint NOT NULL,
	PRIMARY KEY (`ID_POSTAGEM`)
);

CREATE TABLE `TB_TEMA` (
	`ID_TEMA` bigint NOT NULL AUTO_INCREMENT,
	`NOME_TEMA` varchar(30) NOT NULL,
	PRIMARY KEY (`ID_TEMA`)
);

CREATE TABLE `TB_CONSULTA` (
	`ID_CONSULTA` bigint NOT NULL AUTO_INCREMENT,
	`DATA_CONSULTA` DATETIME NOT NULL,
	`DESCRICAO` varchar(300) NOT NULL,
	`ID_USUARIO` bigint NOT NULL,
	PRIMARY KEY (`ID_CONSULTA`)
);

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `TB_USUARIO_fk0` FOREIGN KEY (`ID_ENDERECO`) REFERENCES `TB_ENDERECO`(`ID_ENDERECO`);

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `TB_USUARIO_fk1` FOREIGN KEY (`ID_POSTAGEM`) REFERENCES `TB_POSTAGEM`(`ID_POSTAGEM`);

ALTER TABLE `TB_USUARIO` ADD CONSTRAINT `TB_USUARIO_fk2` FOREIGN KEY (`ID_CONSULTA`) REFERENCES `TB_CONSULTA`(`ID_CONSULTA`);

ALTER TABLE `TB_POSTAGEM` ADD CONSTRAINT `TB_POSTAGEM_fk0` FOREIGN KEY (`ID_TEMA`) REFERENCES `TB_TEMA`(`ID_TEMA`);

ALTER TABLE `TB_CONSULTA` ADD CONSTRAINT `TB_CONSULTA_fk0` FOREIGN KEY (`ID_USUARIO`) REFERENCES `TB_USUARIO`(`ID_USUARIO`);

